/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_action_screenmirror_audio_AudioRecord */

#ifndef _Included_com_action_screenmirror_audio_AudioRecord
#define _Included_com_action_screenmirror_audio_AudioRecord
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_action_screenmirror_audio_AudioRecord
 * Method:    createEngine
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_action_screenmirror_audio_AudioRecord_createEngine
  (JNIEnv *, jclass);

/*
 * Class:     com_action_screenmirror_audio_AudioRecord
 * Method:    createAudioRecord
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_action_screenmirror_audio_AudioRecord_createAudioRecord
  (JNIEnv *, jobject, jstring,jobject);

/*
 * Class:     com_action_screenmirror_audio_AudioRecord
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_action_screenmirror_audio_AudioRecord_stop
  (JNIEnv *, jclass);

/*
 * Class:     com_action_screenmirror_audio_AudioRecord
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_action_screenmirror_audio_AudioRecord_shutdown
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
